version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
      MYSQL_USER: sebas_cruds
      MYSQL_PASSWORD: root
      MYSQL_REQUIRE_SECURE_TRANSPORT: "0"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"